# Generated by Django 3.0.7 on 2020-11-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defineday', models.CharField(default='Great Day', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('write', models.TextField()),
            ],
        ),
    ]
